version: "3.8"

services:
  payment:
    build: ./payment-service
    expose:
      - 3000
    depends_on:
      - user-service
      - order-service

  user:
    build: ./user-service
    expose:
      - 3001

  order:
    build: ./order-service
    ports:
      - "3002:3002"
